{
 "title": "Upload in network monitoring",
 "time": { "from": "2021-05-07T11:49:17.067Z", "to": "2021-05-09T00:21:38.112Z" },
 "panels": [
  {
   "title": "Overall transfer",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  duration\nFROM connections\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Youtube transfer",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'youtube'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'youtube'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Youtube duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  duration\nFROM connections\nWHERE\n  tags->>0 = 'youtube'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  duration\nFROM connections\nWHERE\n  tags->>0 = 'youtube'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Facebook transfer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'facebook'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'facebook'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Facebook transfer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'facebook'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'facebook'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Github transfer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'github'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'github'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Gitub duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  duration\nFROM connections\nWHERE\n  tags->>0 = 'github'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  duration\nFROM connections\nWHERE\n  tags->>0 = 'github'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Google transfer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'google'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  upload\nFROM connections\nWHERE\n  upload < 272783 AND\n  tags->>0 = 'google'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Google duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host1_rdns AS metric,\n  duration\nFROM connections\nWHERE\n  tags->>0 = 'google'\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  host2_rdns AS metric,\n  duration\nFROM connections\nWHERE\n  tags->>0 = 'google'\nORDER BY 1,2"
    }
   ]
  }
 ]
}